# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20150613_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='default_card',
            field=models.ImageField(help_text="Default card for stories in this section that don't specify their own card.", upload_to='organization/section/default_card'),
        ),
        migrations.AlterField(
            model_name='section',
            name='default_card_focus',
            field=models.CharField(choices=[('cc', 'center center'), ('cl', 'center left'), ('cr', 'center right'), ('tl', 'top left'), ('tc', 'top center'), ('tr', 'top right'), ('bl', 'bottom left'), ('bc', 'bottom center'), ('br', 'bottom right')], default='cc', help_text="Location of the focal point for this section's card image.", max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of what this section covers/is about.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='facebook',
            field=models.CharField(blank=True, help_text='Facebook username for this section. Can be found in the URL.', max_length=32),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(help_text='Ordering of this section relative to other sections.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Social media profile image for this section.', upload_to='organization/section/profile_image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(help_text='Used as part of the URL for this section.', max_length=32),
        ),
        migrations.AlterField(
            model_name='section',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter handle for this section, without an "@" symbol.', max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of what this tag is about.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='series',
            field=models.BooleanField(default=False, help_text='Whether or not this tag is forms a series.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Used as part of the URL for this tag.', max_length=32, unique=True),
        ),
    ]
