# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20150505_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mug',
            field=models.ImageField(blank=True, upload_to='core/author/mug/%Y'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter handle, without an "@" symbol.', max_length=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(blank=True, help_text='What the individual in this position is responsible for.', max_length=128),
        ),
    ]
