# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_template_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='file',
            field=models.FileField(upload_to='display/script'),
        ),
        migrations.AlterField(
            model_name='stylesheet',
            name='file',
            field=models.FileField(upload_to='display/stylesheet'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(upload_to='display/template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='scripts',
            field=models.ManyToManyField(blank=True, help_text='Stylesheets to include with this template.', to='display.Script'),
        ),
        migrations.AlterField(
            model_name='template',
            name='stylesheets',
            field=models.ManyToManyField(blank=True, help_text='Stylesheets to include with this template.', to='display.Stylesheet'),
        ),
    ]
