# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20150505_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicrequest',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to an external website for planning associated with this request.'),
        ),
        migrations.AlterField(
            model_name='illustrationrequest',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to an external website for planning associated with this request.'),
        ),
    ]
