# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 20:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20150505_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='attachments/audio/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='attachments/image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Whether or not the poll is currently accepting new responses.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.CharField(help_text='The item being reviewed.', max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating between zero and ten.', null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='The unique ID of this video on YouTube, found in the URL, probably around eleven characters and composed of numbers and letters.', max_length=16),
        ),
    ]
